### ISSUE TITLE
Add ability to donate

### ISSUE THREAD

**Issue by oregonpillow** [TOomaAh/emby_exporter_go#35]
I've been using this awesome dashboard for a while now, and get a lot of value from it. Would love to buy you a coffee if you add a sponsor/donate method.

Cheers!

**Comment by TOomaAh** [comment]
Hello,

Thank you for your request, but I can't accept it.

Unfortunately I had to stop using Emby (reluctantly) because of their 25 device limit.

Unfortunately, I don't know if I'll be able to maintain this project if there are major changes in the api (I'll do my best). 

Just knowing that you're using my project is enough for me :)

**Comment by oregonpillow** [comment]
You horrible person, take my money ;) No worries then and thanks for your kindness! If i notice breaking changes in the future i'll try to submit PRs to fix.
